### ISSUE TITLE
Installing the backend: need enlightment

### ISSUE THREAD

**Issue by clemradio** [roelderickx/connective-plugin-linux#27]
Hi, thanks for the tool. So far I've successfully installed the rest, even though I had to install `pyscard` with the "python3" prefix.

But I don't understand the instructions at the "Installing the backend" section.
Other people have issues with bugs etc, I'm just too dumb to understand those instructions.
"This script" you mean "[connective-backend.py](https://github.com/roelderickx/connective-plugin-linux/blob/main/connective-backend.py)", right?
"Change to the root directory of this repository and run `nativemessaging-install install [browser]`". How do I change to the root directory of a Github repository? What does that mean? Should I open the `connective-downloads` folder as root, then open that folder in a terminal, and then run that "`nativemessaging-install`" command? If that's so, I just got `nativemessaging-install: command not found`. 

Apart from that, everything was clear for a beginner like me.
Please excuse my stupidity.
Cheers

**Comment by roelderickx** [comment]
> Hi, thanks for the tool. So far I've successfully installed the rest, even though I had to install `pyscard` with the "python3" prefix.

Correct.

> But I don't understand the instructions at the "Installing the backend" section. Other people have issues with bugs etc, I'm just too dumb to understand those instructions. "This script" you mean "[connective-backend.py](https://github.com/roelderickx/connective-plugin-linux/blob/main/connective-backend.py)", right? 

That's right.

>"Change to the root directory of this repository and run `nativemessaging-install install [browser]`". How do I change to the root directory of a Github repository? What does that mean? Should I open the `connective-downloads` folder as root, then open that folder in a terminal, and then run that "`nativemessaging-install`" command? If that's so, I just got `nativemessaging-install: command not found`.

The directory is probably named connective-plugin-linux and contains the files you see at [the root of the repository](https://github.com/roelderickx/connective-plugin-linux). You should indeed open a terminal window in that directory.
If the nativemessaging-install command is not available you should install the nativemessaging-ng module. This module is not included in any linux distribution I know of, but can be installed using the command `pip install nativemessaging-ng`.
Your system may complain about the fact that it is externally managed. In that case there are 2 solutions:
* Try the command `pip install nativemessaging-ng --break-system-packages`
* Create a virtual environment using `python -m venv path/to/venv`. Then use `path/to/venv/bin/python` and `path/to/venv/bin/pip` to install the nativemessaging-ng module and the backend.

> 
> Apart from that, everything was clear for a beginner like me. Please excuse my stupidity. Cheers

**Comment by clemradio** [comment]
Thank you for your answer. I will try with someone more experienced.
Thanks again for the plugin, it's a shame government services rely on citizens to all use Windows or MacOS.
