### ISSUE TITLE
module 'smartcard' has no attribute 'System'

### ISSUE THREAD

**Issue by WillemHeremans** [roelderickx/connective-plugin-linux#28]
Hello,

On Ubuntu 20.04 I got the error "module 'smartcard' has no attribute 'System'".

I had to import it explicitly (in the connective-backend.py file):

`import smartcard.System`

I mention it here in case it can help someone.
Regards,

**Comment by roelderickx** [comment]
You're right, somehow later versions of Python do not complain about the lacking import but the import is not wrong either. I added it to make it work on all systems.

Many thanks for reporting!
