### ISSUE TITLE
Document the use of venv to use nativemessaging-ng

### ISSUE THREAD

**Issue by roelderickx** [roelderickx/connective-plugin-linux#31]

**Comment by marnux** [comment]
Just to confirm. On a new system with Debian Sid, installing libpcsclite-dev, allows the installation of all requirements into the venv with ```pip install -r requirements.txt -r optional_requirements.txt```.

**Comment by roelderickx** [comment]
That should do it indeed, I added a step-by-step guide for the uninitiated.
