### ISSUE TITLE
Specify python executable

### ISSUE THREAD

**Issue by swertz** [roelderickx/connective-plugin-linux#6]
Thank you for this! It's unbelievable that citizens running Linux are excluded from now essential services such as itsme...

I was able to use this tool but had some issues with the python executable being used; on ubuntu and derivatives python2 and python3 still coexist, and `python` points to python2 by default. Since I had installed the dependencies for python3, I had to change the shebang to `python3` in https://github.com/roelderickx/connective-plugin-linux/blob/main/connective-backend.py. Is there another way to tell Firefox which python to use?

**Comment by BrechtSerckx** [comment]
I would think that a `#! /usr/bin/env python3` would work, not sure it's supported on all systems.

**Comment by swertz** [comment]
Yes that is what I did and it worked, perhaps this could be highlighted for other users?

**Comment by BrechtSerckx** [comment]
Yeah I think just changing the line from `#! /usr/bin/env python3` should work everywhere.

**Comment by swertz** [comment]
Yes, I suppose the `python3` alias is available on most systems...

**Comment by roelderickx** [comment]
> Thank you for this! It's unbelievable that citizens running Linux are excluded from now essential services such as itsme...

I am not sure it is essential as I have no smartphone and I'd like to keep it that way for as long as possible 🙂 

> Yes, I suppose the python3 alias is available on most systems...

I think so too. On my system python points to python3 but I will modify the shebang this evening to python3 when I am back at my own computer.

**Comment by roelderickx** [comment]
Fixed and pushed to the main branch.
