### ISSUE TITLE
Add support for belpic v1.8 identity cards

### ISSUE THREAD

**Issue by roelderickx** [roelderickx/connective-plugin-linux#8]
The new belgian identity cards (belpic v1.8) only support the ECDSA signing algorithm, while previous versions only support the RSA signing algorithm. It is not clear how the Connective application deals with this. To be investigated and implemented.

**Comment by roelderickx** [comment]
Was pull request #17 the only change necessary to make it work @vhdirk ?

**Comment by vhdirk** [comment]
Yup. Or at least for what I needed it. I just added the ATR and bingo :)

**Comment by roelderickx** [comment]
Excellent :slightly_smiling_face: 
Many thanks!
